###
# @name login
POST https://localhost:7000/api/account/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Abc123!!!"
}

###
GET https://localhost:7000/api/admin/users-with-roles
Authorization: bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMSIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJyb2xlIjpbIkFkbWluIiwiTW9kZXJhdG9yIl0sIm5iZiI6MTY5MzYyODQ3NiwiZXhwIjoxNjkzNjYwODc2LCJpYXQiOjE2OTM2Mjg0NzZ9.h-7GlmqVkF9P_70O17_63N-5cb2szVRPbDXVtd7ZiQDxe5YS3HeIlaACDj1vRTonfF5olDadPt0PNN8xTVt0PQ


###
POST https://localhost:7000/api/admin/users-with-roles
Authorization: bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMSIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJyb2xlIjpbIkFkbWluIiwiTW9kZXJhdG9yIl0sIm5iZiI6MTY5MzYyODQ3NiwiZXhwIjoxNjkzNjYwODc2LCJpYXQiOjE2OTM2Mjg0NzZ9.h-7GlmqVkF9P_70O17_63N-5cb2szVRPbDXVtd7ZiQDxe5YS3HeIlaACDj1vRTonfF5olDadPt0PNN8xTVt0PQ
